name: Cypress CI Tests

on:
  # Manual button click from the GitHub UI
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          record: true
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: cypress/videos
